server:
  port: 8101
spring:
  application:
    name: userservice
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:8897/cloudstudy
    username: root
    password: pswonlyforlocal
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka